name: Pytest

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code without submodules
      - name: Checkout repository without submodules
        run: |
          git clone --depth 1 https://github.com/humemai/humemai.git humemai
          cd humemai
          git checkout ${{ github.ref_name }}

      # Install Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker setup info
        run: |
          docker version
          docker info

      # Install docker-compose
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Verify docker-compose installation
        run: docker-compose version

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Upgrade pip and build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pytest

      # Install the package from the cloned repository
      - name: Install humemai package
        run: |
          cd humemai
          python -m pip install .

      # Run pytest
      - name: Run pytest
        env:
          DOCKER_BUILDKIT: 1
        run: |
          cd humemai
          python -m pytest .
